### PR TITLE
Add data binding support

### PR DESCRIPTION
**Pull request by jpaya17**
I've added a first version support of data binding to all application views.

### CODE REVIEW

**Comment by igorwojda** [comment]
Nice PR - one small change - we should remove `data binding` from `Upcoming improvements` in `README.md`

**Comment by jpaya17** [comment]
You're right Igor, I completely forgot it! Done :)

**Comment by igorwojda** [comment]
It took me a while. PR looks good.
Now it conflicts with some of the recent changes, can you please update this PR (I can't easily do it).

**Comment by igorwojda** [comment]
Some time has passed, but your PR inspired me to implement vide bindings https://github.com/igorwojda/android-showcase/pull/130.

I will close this for now.

**Pull request closed without merging**
